"""Shared helper for scripts/site/: write a data file for the site with a header that says where it came from.

Every file in site/data/ starts with:
  - the script that made it, the time it ran (Mac local time) and the git commit it ran on
    ("+ uncommitted changes" if the scripts or inputs had changes not yet committed);
  - every input file with its SHA-256, so anyone can check they are using the same inputs;
  - notes on judgment calls.
Run the scripts from the repo root.
"""
import datetime
import hashlib
import json
import subprocess


def sha256(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def git_commit():
    sha = subprocess.run(["git", "rev-parse", "--short", "HEAD"], capture_output=True, text=True).stdout.strip()
    dirty = subprocess.run(["git", "status", "--porcelain", "--", "scripts/site", "data/processed", "viz/pm25-scrolly"],
                           capture_output=True, text=True).stdout.strip()
    return sha + (" + uncommitted changes" if dirty else "")


def write_js(out, var, obj, script, inputs, notes=()):
    now = datetime.datetime.now().astimezone().strftime("%Y-%m-%d %H:%M %Z")
    head = [f"// Generated by {script} on {now}, commit {git_commit()}. Do not edit by hand: change the script and re-run it.",
            "// Inputs (SHA-256):"]
    head += [f"//   {p}  {sha256(p)}" for p in sorted(set(inputs))]
    head += [f"// {n}" for n in notes]
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(head) + "\n")
        f.write(f"window.{var}=" + json.dumps(obj, ensure_ascii=False, separators=(",", ":")) + ";\n")
    print(f"wrote {out}")
